const handler = async (m, { conn }) => {
  const tristes = [
    'A veces duele más no saber que saber.',
    'El silencio es la respuesta más cruel.',
    'Las personas van y vienen, pero los recuerdos se quedan.',
    'No todo lo que brilla es oro, ni todo lo que duele se ve.',
    'El amor es como el viento, no puedes verlo pero puedes sentirlo.',
    'Las despedidas duelen, pero las que no se dan duelen más.',
    'A veces la persona que más extrañas es la que nunca tuviste.',
    'El tiempo no cura, solo enseña a vivir con el dolor.',
    'Las lágrimas son palabras que el corazón no puede decir.',
    'No duele perder, duele haber tenido y perder.',
    'El amor propio es el amor más difícil de encontrar.',
    'La soledad no es estar solo, es sentirse solo estando acompañado.',
    'A veces sonreímos para no mostrar lo que sentimos.',
    'Los recuerdos son la única prueba de que existimos.',
    'El dolor es inevitable, el sufrimiento es opcional.',
    'No hay peor ciego que el que no quiere ver.',
    'El corazón tiene razones que la razón no entiende.',
    'El tiempo no espera, pero el dolor sí.',
    'Las promesas son como el papel, se rompen fácilmente.',
    'A veces el olvido es la única venganza.',
    'El amor no correspondido es la herida que nunca cierra.',
    'Extrañar a alguien es saber que una parte de ti se fue con esa persona.',
    'Los abrazos de alguien que ya no está son los que más se extrañan.',
    'A veces el silencio es el grito más fuerte que puedes dar.',
    'La vida es un suspiro y luego el vacío.',
    'Las noches son más largas cuando no hay a quien abrazar.',
    'La tristeza es el eco de la felicidad que se fue.',
    'El corazón no olvida, solo aprende a vivir con cicatrices.',
    'La distancia no mide kilómetros, mide recuerdos.',
    'Los sueños se desvanecen cuando la realidad te despierta a golpes.',
    'El miedo a perder es el mejor aliado de la soledad.',
    'A veces las personas se van sin decir adiós, solo se convierten en recuerdos.',
    'El amor es un fuego que quema lento cuando no hay quien lo avive.',
    'La esperanza es la última en morir, pero cuando muere, todo termina.',
    'La vida es una colección de momentos, pero los vacíos pesan más.',
    'No hay peor soledad que la que sientes cuando estás rodeado de gente.',
    'El olvido es el premio de los que saben soltar.',
    'La felicidad es un espejismo que perseguimos sin saber que somos nosotros.',
    'A veces el corazón se rompe sin que nadie lo vea.',
    'El tiempo no perdona, solo dicta sentencia.',
    'Las mentiras duelen, pero las verdades que callas duelen más.',
    'El amor es un juego donde algunos ganan y otros aprenden.',
    'La ausencia no se mide en días, sino en el peso del vacío que deja.',
    'Los abrazos de alguien que ya no está son los que más se extrañan.',
    'El alma se oscurece cuando la luz del amor se apaga.',
    'Hay heridas que ni el tiempo puede curar.',
    'La tristeza es la sombra del corazón que no encuentra paz.',
    'El desamor es el silencio después de la tormenta.',
    'A veces el perdón es más para uno mismo que para el otro.',
    'La vida es un largo adiós.',
    'El amor es una partida de ajedrez donde algunos pierden la reina.',
    'No hay manual para sobrevivir a la pérdida.',
    'Las risas que compartiste se convierten en lágrimas en la soledad.',
    'El pasado es un fantasma que no te deja avanzar.',
    'La luna es testigo de las noches de desvelo.',
    'Las estrellas no brillan igual cuando estás triste.',
    'El viento trae recuerdos que quisieras olvidar.',
    'El mar es el único que guarda todos tus secretos.',
    'La lluvia lava la tristeza, pero el frío queda.',
    'El invierno del alma no tiene primavera.',
    'Los días grises son el reflejo de un corazón apagado.',
    'El silencio es la única respuesta que no duele.',
    'A veces las palabras sobran, pero las lágrimas no.',
    'El amor no se termina, solo se transforma en recuerdo.',
    'La soledad es el precio de haber amado demasiado.',
    'No hay cura para la nostalgia.',
    'El tiempo pasa, pero las cicatrices quedan.',
    'A veces la vida te quita lo que más quieres para enseñarte a valorar.',
    'La felicidad es un suspiro que se escapa cuando no miras.',
    'El corazón se rompe en silencio, pero el ruido lo hace todo.',
    'La distancia entre dos personas no se mide en metros, sino en silencios.',
    'Los abrazos se vuelven aire cuando la persona se va.',
    'El amor no se busca, se encuentra, y cuando se va, se extraña.',
    'La vida es una rueda, pero a veces te quedas atascado.',
    'Las promesas son el papel que el viento se lleva.',
    'La noche es el manto de los corazones rotos.',
    'La luna llena es un ojo que observa tu dolor.',
    'Los recuerdos son cadenas que no te dejan caminar.',
    'El ayer es un ladrón que roba el hoy.',
    'La incertidumbre es el peor enemigo de la paz.',
    'El amor a veces es un error que pagas con lágrimas.',
    'La despedida es la cicatriz que no se ve pero duele.',
    'El corazón no entiende de razones.',
    'La vida no te da lo que quieres, te da lo que necesitas, y a veces duele.',
    'La tristeza es el reflejo de un corazón que amó en vano.',
    'Los días se vuelven eternos cuando esperas a alguien que no vuelve.',
    'El olvido es el único consuelo para un amor perdido.',
    'La ausencia deja un vacío que nada puede llenar.',
    'El amor es un fuego que se apaga cuando dejas de alimentarlo.',
    'Las lágrimas son la sangre del alma herida.',
    'El tiempo no te devuelve lo que perdiste, solo te enseña a vivir sin ello.',
    'La soledad es la casa de los corazones rotos.',
    'El pasado duele, pero el futuro asusta.',
    'El presente es todo lo que tienes, pero a veces no lo valoras.',
    'La vida es una oportunidad, pero a veces llegas tarde.',
    'El amor es un viaje sin regreso cuando se termina.',
    'Las palabras de amor se convierten en viento cuando se van.',
    'La esperanza es un hilo delgado que se corta fácilmente.',
    'El sufrimiento es el profesor más duro de la vida.',
    'La alegría se desvanece cuando la tristeza la opaca.',
    'El corazón no se olvida, solo se acostumbra al vacío.',
    'La vida es un suspiro que se convierte en eco.',
    'El amor es un refugio que a veces se convierte en prisión.',
    'La distancia es el puente entre el amor y el olvido.',
    'Los recuerdos son el tesoro que duele poseer.',
    'La espera es la peor compañía en la soledad.',
    'El desamor es el invierno del alma.',
    'La vida te da sorpresas, pero no todas son buenas.',
    'El llanto es la liberación del alma.',
    'El dolor es el maestro que enseña a vivir.',
    'La tristeza es la sombra que sigue al amor cuando se va.',
    'El olvido es la muerte del amor.',
    'El amor es un fuego que quema cuando no hay quien lo apague.',
    'La vida es un libro, pero algunos capítulos son tristes.',
    'Las estrellas caen cuando lloras.',
    'La luna se esconde cuando el corazón está roto.',
    'El cielo se vuelve gris cuando el alma está oscura.',
    'La lluvia es el llanto del cielo.',
    'El viento se lleva las palabras que no dijiste.',
    'El mar guarda tus secretos pero no tus lágrimas.',
    'La arena del tiempo borra las huellas del amor.',
    'Los árboles se quedan sin hojas en el otoño del alma.',
    'La primavera no llega cuando el corazón está en invierno.',
    'El verano es un espejismo de felicidad.',
    'El otoño es la estación de las despedidas.',
    'El invierno es el silencio del alma.',
    'La luz se apaga cuando la tristeza llega.',
    'La oscuridad es la cobija del dolor.',
    'Los sueños se quiebran como el vidrio.',
    'La esperanza es un pájaro que vuela lejos.',
    'El amor es un camino que a veces no tiene regreso.',
    'La amistad es el refugio en la tormenta.',
    'El tiempo es un río que arrastra todo.',
    'La memoria es el eco del corazón.',
    'El corazón tiene memoria, pero duele recordar.',
    'La vida es un viaje sin mapa.',
    'La felicidad es un destino que pocos alcanzan.',
    'La tristeza es el precio de haber amado.',
    'El dolor es la cicatriz del alma.',
    'El silencio es la respuesta que más duele.',
    'La soledad es la compañera del olvido.',
    'El amor es una herida que no cierra.',
    'La vida es un instante que se escapa.',
    'Los recuerdos son las cadenas del pasado.',
    'El futuro es incierto, pero el pasado duele.',
    'El presente es un regalo que no siempre recibes.',
    'La esperanza es un sueño que se desvanece.',
    'El desamor es la muerte del corazón.',
    'La distancia es el veneno del amor.',
    'La ausencia es el dolor del alma.',
    'El olvido es la cura del corazón roto.',
    'La vida es una ruleta rusa.',
    'El amor es una apuesta que a veces se pierde.',
    'La tristeza es el reflejo del alma.',
    'El dolor es el compañero del amor perdido.',
    'La soledad es el silencio del corazón.',
    'El tiempo no detiene el dolor.',
    'Las lágrimas son el idioma del alma.',
    'El amor es un sueño que se convierte en pesadilla.',
    'La despedida es el final de una historia.',
    'El recuerdo es la herida que no cierra.',
    'La esperanza es un hilo que se rompe.',
    'El olvido es la única liberación.',
    'La vida es un acertijo sin solución.',
    'El amor es un misterio sin respuesta.',
    'La tristeza es la sombra del corazón.',
    'El dolor es el eco de la felicidad perdida.',
    'La soledad es el abismo del alma.',
    'El tiempo es el ladrón de los sueños.',
    'Las lágrimas son la poesía del dolor.',
    'El amor es una llama que se apaga.',
    'La despedida es el silencio que sigue.',
    'El recuerdo es la prisión del alma.',
    'La esperanza es un faro en la oscuridad.',
    'El olvido es la paz del corazón.',
    'La vida es una canción triste.',
    'El amor es un poema inconcluso.',
    'La tristeza es la melodía del alma.',
    'El dolor es el latido del corazón roto.',
    'La soledad es el refugio del cansancio.',
    'El tiempo es el juez de los sentimientos.',
    'Las lágrimas son el consuelo del alma.',
    'El amor es un sueño que se desvanece.',
    'La despedida es el adiós que nunca se olvida.',
    'El recuerdo es la compañía del vacío.',
    'La esperanza es la luz que se apaga.',
    'El olvido es la llave de la libertad.',
    'La vida es un laberinto sin salida.',
    'El amor es un laberinto de emociones.',
    'La tristeza es el eco del alma.',
    'El dolor es el grito del corazón.',
    'La soledad es la ausencia de ti.',
    'El tiempo no cura, solo alivia.',
    'Las lágrimas son la oración del dolor.',
    'El amor es un fuego que arde sin combustible.',
    'La despedida es el inicio del olvido.',
    'El recuerdo es la herida que sangra.',
    'La esperanza es la ilusión del deseo.',
    'El olvido es el sueño del corazón.',
    'La vida es un verso sin rima.',
    'El amor es un capítulo cerrado.',
    'La tristeza es la novela del alma.',
    'El dolor es el personaje principal.',
    'La soledad es el escenario vacío.',
    'El tiempo es el narrador incansable.',
    'Las lágrimas son las páginas mojadas.',
    'El amor es el título borrado.',
    'La despedida es el punto final.',
    'El recuerdo es el epílogo sin fin.',
    'La esperanza es el prólogo de un nuevo amanecer.',
    'El olvido es el cierre del libro.',
    'La vida es un poema que escribimos sin saber.',
    'El amor es la estrofa más bella.',
    'La tristeza es el ritmo lento.',
    'El dolor es la pausa necesaria.',
    'La soledad es el silencio entre versos.',
    'El tiempo es el compás que marca el paso.',
    'Las lágrimas son la rima del sentimiento.',
    'El amor es la canción que se escapa.',
    'La despedida es la nota final.',
    'El recuerdo es el eco de la melodía.',
    'La esperanza es el acorde que resuena.',
    'El olvido es la ausencia de música.',
    'La vida es una obra de teatro sin ensayo.',
    'El amor es el personaje principal.',
    'La tristeza es el drama del acto.',
    'El dolor es la escena más dura.',
    'La soledad es el monólogo interior.',
    'El tiempo es el director del destino.',
    'Las lágrimas son el aplauso del alma.',
    'El amor es el guión que se rompe.',
    'La despedida es el telón que cae.',
    'El recuerdo es la función continua.',
    'La esperanza es el ensayo de otra función.',
    'El olvido es el teatro vacío.',
    'La vida es un viaje sin mapa ni brújula.',
    'El amor es el destino que nunca llegas.',
    'La tristeza es el paisaje del camino.',
    'El dolor es la lluvia en la travesía.',
    'La soledad es el equipaje que llevas.',
    'El tiempo es la carretera infinita.',
    'Las lágrimas son el combustible del alma.',
    'El amor es la gasolina de los sueños.',
    'La despedida es la estación de tren.',
    'El recuerdo es el billete que guardas.',
    'La esperanza es el próximo destino.',
    'El olvido es el final del trayecto.',
    'La vida es un sueño del que nunca despiertas.',
    'El amor es la ilusión que te mantiene dormido.',
    'La tristeza es la pesadilla que te despierta.',
    'El dolor es la realidad que te golpea.',
    'La soledad es el vacío que te rodea.',
    'El tiempo es el reloj que nunca se detiene.',
    'Las lágrimas son la lluvia que te limpia.',
    'El amor es el arcoíris que aparece después.',
    'La despedida es la tormenta que pasa.',
    'El recuerdo es la huella que queda.',
    'La esperanza es el sol que vuelve a brillar.',
    'El olvido es la nube que se disipa.'
  ]

  const triste = tristes[Math.floor(Math.random() * tristes.length)]

  await m.react('😢')
  await m.reply([
    `╔══〔 🌼 *THEELY-MD — TRISTE* 〕══╗`,
    `║`,
    `║  💔 *Reflexión del día:*`,
    `║`,
    `║  📝 "${triste}"`,
    `║`,
    `║  😢 *A veces la vida duele*`,
    `╚══════════════════════════════════╝`
  ].join('\n'))
}

handler.help = ['triste']
handler.tags = ['fun']
handler.command = ['triste', 'sad', 'tristeza']
handler.register = true
handler.desc = 'Frases tristes y reflexivas'
export default handler