const FRASES = [
  { texto: 'El poder no viene de nada fácil. Se forja en el dolor y la determinación.', autor: 'Goku — Dragon Ball' },
  { texto: 'Si no luchas por lo que quieres, no llores por lo que pierdes.', autor: 'Proverbio' },
  { texto: 'El fracaso es simplemente la oportunidad de comenzar de nuevo, pero con más inteligencia.', autor: 'Henry Ford' },
  { texto: 'No importa cuántas veces caigas, sino cuántas veces te levantes.', autor: 'Naruto Uzumaki' },
  { texto: 'La diferencia entre lo posible y lo imposible está en la determinación.', autor: 'Tommy Lasorda' },
  { texto: 'No llores porque terminó, sonríe porque sucedió.', autor: 'Dr. Seuss' },
  { texto: 'El único modo de hacer un gran trabajo es amar lo que haces.', autor: 'Steve Jobs' },
  { texto: 'Sé el cambio que quieres ver en el mundo.', autor: 'Gandhi' },
  { texto: 'Los sueños no funcionan si tú no lo haces.', autor: 'John C. Maxwell' },
  { texto: 'No busques encontrarte a ti mismo. Crea quién quieres ser.', autor: 'Anónimo' },
  { texto: 'La fuerza no viene del cuerpo físico, viene de una voluntad indomable.', autor: 'Mahatma Gandhi' },
  { texto: 'Nunca sabrás de lo que eres capaz hasta que lo intentes.', autor: 'Anónimo' },
  { texto: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', autor: 'Robert Collier' },
  { texto: 'La vida es lo que pasa mientras estás ocupado haciendo otros planes.', autor: 'John Lennon' },
  { texto: 'En medio de las dificultades yace la oportunidad.', autor: 'Albert Einstein' },
  { texto: 'No te rindas, el principio siempre es lo más difícil.', autor: 'Anónimo' },
  { texto: 'El coraje no es la ausencia de miedo, sino la decisión de actuar a pesar de él.', autor: 'Nelson Mandela' },
  { texto: 'La vida es 10% lo que te sucede y 90% cómo reaccionas.', autor: 'Charles R. Swindoll' },
  { texto: 'El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo.', autor: 'Winston Churchill' },
  { texto: 'La mejor venganza es un éxito rotundo.', autor: 'Frank Sinatra' },
  { texto: 'Si puedes soñarlo, puedes lograrlo.', autor: 'Walt Disney' },
  { texto: 'El único lugar donde el éxito viene antes que el trabajo es en el diccionario.', autor: 'Vidal Sassoon' },
  { texto: 'No importa lo lento que vayas, mientras no te detengas.', autor: 'Confucio' },
  { texto: 'El fracaso es el condimento que da sabor al éxito.', autor: 'Truman Capote' },
  { texto: 'La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra.', autor: 'Walter Elliot' },
  { texto: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', autor: 'Eleanor Roosevelt' },
  { texto: 'La única forma de hacer un gran trabajo es amar lo que haces.', autor: 'Steve Jobs' },
  { texto: 'No esperes el momento perfecto, haz que el momento sea perfecto.', autor: 'Anónimo' },
  { texto: 'Cree en ti mismo y todo será posible.', autor: 'Anónimo' },
  { texto: 'La vida es una aventura atrevida o no es nada.', autor: 'Helen Keller' },
  { texto: 'El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje.', autor: 'Winston Churchill' },
  { texto: 'La gente que es lo suficientemente loca como para pensar que puede cambiar el mundo es la que lo hace.', autor: 'Steve Jobs' },
  { texto: 'El verdadero viaje del descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.', autor: 'Marcel Proust' },
  { texto: 'La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.', autor: 'John Lennon' },
  { texto: 'No hay viento favorable para el que no sabe a dónde va.', autor: 'Séneca' },
  { texto: 'El éxito es la consecuencia de la preparación, el trabajo duro y el aprendizaje del fracaso.', autor: 'Colin Powell' },
  { texto: 'La determinación es la clave del éxito.', autor: 'Anónimo' },
  { texto: 'El único fracaso es no intentarlo.', autor: 'Anónimo' },
  { texto: 'La felicidad no es algo hecho. Viene de tus propias acciones.', autor: 'Dalai Lama' },
  { texto: 'El propósito de la vida es tener una vida con propósito.', autor: 'Anónimo' },
  { texto: 'La mejor manera de predecir el futuro es creándolo.', autor: 'Peter Drucker' },
  { texto: 'No te tomes la vida demasiado en serio, no vas a salir vivo de ella.', autor: 'Anónimo' },
  { texto: 'El éxito es aprender a ir de fracaso en fracaso sin perder el entusiasmo.', autor: 'Winston Churchill' },
  { texto: 'La paciencia es amarga, pero sus frutos son dulces.', autor: 'Jean-Jacques Rousseau' },
  { texto: 'La vida es un 10% lo que te pasa y un 90% cómo reaccionas.', autor: 'Charles Swindoll' },
  { texto: 'No hay caminos para la paz; la paz es el camino.', autor: 'Mahatma Gandhi' },
  { texto: 'El mundo es un lugar peligroso. No por la gente mala, sino por aquellos que no hacen nada al respecto.', autor: 'Albert Einstein' },
  { texto: 'La verdadera medida de un hombre no es cómo se comporta en momentos de confort, sino cómo se comporta en tiempos de controversia.', autor: 'Martin Luther King Jr.' },
  { texto: 'La educación es el arma más poderosa que puedes usar para cambiar el mundo.', autor: 'Nelson Mandela' },
  { texto: 'La vida es como una bicicleta, para mantener el equilibrio debes seguir adelante.', autor: 'Albert Einstein' },
  { texto: 'No hay nada que temer, solo hay que entender.', autor: 'Marie Curie' },
  { texto: 'La única persona que estás destinado a ser eres la persona que decides ser.', autor: 'Ralph Waldo Emerson' },
  { texto: 'La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento.', autor: 'Anónimo' },
  { texto: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', autor: 'Robert Collier' },
  { texto: 'El fracaso es la oportunidad de empezar de nuevo con más inteligencia.', autor: 'Henry Ford' },
  { texto: 'No hay nada que no puedas lograr si crees en ti mismo.', autor: 'Anónimo' },
  { texto: 'La felicidad es la consecuencia de la acción.', autor: 'Anónimo' },
  { texto: 'La vida es como una caja de bombones, nunca sabes lo que te va a tocar.', autor: 'Forrest Gump' },
  { texto: 'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.', autor: 'Proverbio chino' },
  { texto: 'La paciencia es la clave de la felicidad.', autor: 'Anónimo' },
  { texto: 'No llores porque se fue, sonríe porque estuvo.', autor: 'Anónimo' },
  { texto: 'El amor es la única fuerza capaz de transformar a un enemigo en amigo.', autor: 'Martin Luther King Jr.' },
  { texto: 'La vida es como una obra de teatro; no importa cuánto dure, sino lo bien que se represente.', autor: 'Séneca' },
  { texto: 'El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace.', autor: 'León Tolstói' },
  { texto: 'La mejor forma de predecir el futuro es crearlo.', autor: 'Peter Drucker' },
  { texto: 'La vida no es un problema a resolver, sino una realidad a experimentar.', autor: 'Søren Kierkegaard' },
  { texto: 'El miedo es la enfermedad más contagiosa y la más difícil de curar.', autor: 'Anónimo' },
  { texto: 'No hay nada imposible, solo hay cosas que aún no se han intentado.', autor: 'Anónimo' },
  { texto: 'La verdadera riqueza es la salud y la felicidad.', autor: 'Anónimo' },
  { texto: 'La vida es como un espejo; te devuelve lo que le das.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio de la perseverancia.', autor: 'Anónimo' },
  { texto: 'La única manera de hacer un gran trabajo es amar lo que haces.', autor: 'Steve Jobs' },
  { texto: 'El fracaso es la base del éxito.', autor: 'Anónimo' },
  { texto: 'La vida es una aventura, no una rutina.', autor: 'Anónimo' },
  { texto: 'El tiempo es el mejor consejero.', autor: 'Anónimo' },
  { texto: 'La felicidad no es un destino, es una forma de viajar.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada día es una página nueva.', autor: 'Anónimo' },
  { texto: 'El verdadero amor no se encuentra, se construye.', autor: 'Anónimo' },
  { texto: 'La esperanza es la última que muere.', autor: 'Proverbio' },
  { texto: 'La vida es un sueño, pero hay que despertar.', autor: 'Anónimo' },
  { texto: 'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.', autor: 'Albert Schweitzer' },
  { texto: 'Si quieres algo que nunca has tenido, tienes que hacer algo que nunca has hecho.', autor: 'Thomas Jefferson' },
  { texto: 'La paciencia es la virtud de los fuertes.', autor: 'Anónimo' },
  { texto: 'La vida es como una montaña rusa; tiene subidas y bajadas, pero siempre es emocionante.', autor: 'Anónimo' },
  { texto: 'El amor es la única cosa que crece cuando se comparte.', autor: 'Anónimo' },
  { texto: 'La verdadera amistad es como un árbol, necesita tiempo para crecer.', autor: 'Anónimo' },
  { texto: 'La vida es un regalo, no un derecho.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la acción.', autor: 'Anónimo' },
  { texto: 'No hay mal que por bien no venga.', autor: 'Proverbio' },
  { texto: 'La vida es como una caja de sorpresas.', autor: 'Anónimo' },
  { texto: 'El tiempo es el mejor remedio para el dolor.', autor: 'Anónimo' },
  { texto: 'La felicidad es una elección, no un resultado.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada momento es una nota.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza más poderosa del universo.', autor: 'Anónimo' },
  { texto: 'La esperanza es el sueño del hombre despierto.', autor: 'Aristóteles' },
  { texto: 'La vida es como una taza de café; amarga pero necesaria.', autor: 'Anónimo' },
  { texto: 'El éxito es la suma de pequeños esfuerzos.', autor: 'Robert Collier' },
  { texto: 'La vida es como un río; fluye sin descanso.', autor: 'Anónimo' },
  { texto: 'La verdadera belleza está en el interior.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada paso cuenta.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que guía el camino.', autor: 'Anónimo' },
  { texto: 'La esperanza es la fuerza que mueve al mundo.', autor: 'Anónimo' },
  { texto: 'La vida es como un poema; cada palabra importa.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la perseverancia.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; solo nosotros podemos hacerlo realidad.', autor: 'Anónimo' },
  { texto: 'El amor es la energía que lo transforma todo.', autor: 'Anónimo' },
  { texto: 'La esperanza es la luz en la oscuridad.', autor: 'Anónimo' },
  { texto: 'La vida es como un juego; hay que jugarlo con pasión.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la determinación.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que cultivarlo.', autor: 'Anónimo' },
  { texto: 'El amor es la mejor medicina.', autor: 'Anónimo' },
  { texto: 'La esperanza es la fe en el futuro.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; solo nosotros lo creamos.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa del esfuerzo.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada día es una aventura.', autor: 'Anónimo' },
  { texto: 'El amor es la única verdad.', autor: 'Anónimo' },
  { texto: 'La esperanza es el aliento de la vida.', autor: 'Anónimo' },
  { texto: 'La vida es como una obra de arte; hay que crearla.', autor: 'Anónimo' },
  { texto: 'El éxito es el fruto de la constancia.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; hay que cantarla.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que nos une.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos mantiene vivos.', autor: 'Anónimo' },
  { texto: 'La vida es como un regalo; hay que disfrutarlo.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la pasión.', autor: 'Anónimo' },
  { texto: 'La vida es como un desafío; hay que superarlo.', autor: 'Anónimo' },
  { texto: 'El amor es la respuesta a todo.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace fuertes.', autor: 'Anónimo' },
  { texto: 'La vida es como un aprendizaje; cada día una lección.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo esfuerzo.', autor: 'Anónimo' },
  { texto: 'La vida es como una danza; hay que moverte.', autor: 'Anónimo' },
  { texto: 'El amor es el verdadero sentido.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos impulsa.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; hay que pintarlo.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa del trabajo.', autor: 'Anónimo' },
  { texto: 'La vida es como un río; fluye sin detenerse.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que ilumina.', autor: 'Anónimo' },
  { texto: 'La esperanza es la chispa de la vida.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; hay que escribirlo.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador.', autor: 'Anónimo' },
  { texto: 'La vida es como una estrella; brilla con luz propia.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que transforma.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da alas.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; hay que vivirlo.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la fe.', autor: 'Anónimo' },
  { texto: 'La vida es como un espejo; refleja lo que eres.', autor: 'Anónimo' },
  { texto: 'El amor es la única magia.', autor: 'Anónimo' },
  { texto: 'La esperanza es el motor del mundo.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada paso te lleva a un destino.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la lucha.', autor: 'Anónimo' },
  { texto: 'La vida es como un juego; hay que jugarlo con pasión.', autor: 'Anónimo' },
  { texto: 'El amor es la respuesta a todas las preguntas.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos guía.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; hay que cantarla con el corazón.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo esfuerzo sincero.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que regarlo con amor.', autor: 'Anónimo' },
  { texto: 'El amor es la energía que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace soñar.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; hay que pintarlo con colores vivos.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la dedicación.', autor: 'Anónimo' },
  { texto: 'La vida es como un río; hay que dejarse llevar.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que ilumina el camino.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos mantiene en pie.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada día una página nueva.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador que nunca se rinde.', autor: 'Anónimo' },
  { texto: 'La vida es como una estrella; brillas incluso en la oscuridad.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da fuerza.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; tú eres el protagonista.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio a la constancia.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; disfruta el camino.', autor: 'Anónimo' },
  { texto: 'El amor es la magia que todo lo transforma.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace seguir adelante.', autor: 'Anónimo' },
  { texto: 'La vida es como un juego; hay que jugarlo con alegría.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo esfuerzo sincero.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada momento una nota.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que guía nuestra vida.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace crecer.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que cuidarlo con amor.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa de la fe.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta tu propia obra.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo une.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace libres.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; vive cada instante.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador que nunca se rinde.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; escribe tu propia historia.', autor: 'Anónimo' },
  { texto: 'El amor es la única verdad eterna.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da propósito.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada día una aventura.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio a la perseverancia.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; canta con pasión.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo sana.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos ilumina.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; crea tu propia realidad.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la acción.', autor: 'Anónimo' },
  { texto: 'La vida es como un juego; vive con intensidad.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace inmortales.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; tú eres el artista.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la determinación.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada paso es importante.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo transforma.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da valor.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada capítulo es una enseñanza.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada nota es un sentimiento.', autor: 'Anónimo' },
  { texto: 'El amor es la energía que todo lo mueve.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da vida.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que sembrar amor.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa del esfuerzo.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta tu futuro.', autor: 'Anónimo' },
  { texto: 'El amor es la única verdad.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace avanzar.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; vive con intensidad.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio a la constancia.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; disfruta cada momento.', autor: 'Anónimo' },
  { texto: 'El amor es la magia que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos guía.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada página es una oportunidad.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la perseverancia.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; canta con alegría.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo ilumina.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace soñar.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que florecer.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la fe.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; crea tu obra maestra.', autor: 'Anónimo' },
  { texto: 'El amor es la única energía eterna.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da fuerza.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; tú eres el creador.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo esfuerzo.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada paso te acerca al destino.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace libres.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada día una historia.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa de la dedicación.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada nota es un instante.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo sana.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos mantiene vivos.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que cultivarlo con cariño.', autor: 'Anónimo' },
  { texto: 'El éxito es el fruto de la constancia.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta con pasión.', autor: 'Anónimo' },
  { texto: 'El amor es la única magia que todo lo transforma.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace grandes.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; vive cada instante con intensidad.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador que nunca se rinde.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada experiencia es un aprendizaje.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo conecta.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da alas para volar.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; escribe tu propia leyenda.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio al trabajo duro.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; canta con el corazón.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que guía nuestros pasos.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace brillar.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que regarlo con alegría.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la perseverancia.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta tu propio destino.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace inmortales.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; tú eres el protagonista.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo esfuerzo sincero.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada día es una nueva oportunidad.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que ilumina la oscuridad.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da propósito.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada capítulo es una lección.', autor: 'Anónimo' },
  { texto: 'El éxito es la recompensa a la fe.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada nota es un sentimiento.', autor: 'Anónimo' },
  { texto: 'El amor es la energía que todo lo transforma.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace fuertes.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que florecer con amor.', autor: 'Anónimo' },
  { texto: 'El éxito es el resultado de la determinación.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta tu propia realidad.', autor: 'Anónimo' },
  { texto: 'El amor es la única verdad eterna.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da valor.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; vive con intensidad.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada paso es importante.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo sana.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos guía.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; cada día una historia.', autor: 'Anónimo' },
  { texto: 'El éxito es la consecuencia de la constancia.', autor: 'Anónimo' },
  { texto: 'La vida es como una canción; cada nota es un instante.', autor: 'Anónimo' },
  { texto: 'El amor es la luz que todo lo ilumina.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace soñar.', autor: 'Anónimo' },
  { texto: 'La vida es como un jardín; hay que cultivarlo con pasión.', autor: 'Anónimo' },
  { texto: 'El éxito es el premio al esfuerzo.', autor: 'Anónimo' },
  { texto: 'La vida es como un lienzo; pinta con pasión.', autor: 'Anónimo' },
  { texto: 'El amor es la única magia que todo lo puede.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos hace avanzar.', autor: 'Anónimo' },
  { texto: 'La vida es como un sueño; tú eres el creador.', autor: 'Anónimo' },
  { texto: 'El éxito es la meta de todo soñador que nunca se rinde.', autor: 'Anónimo' },
  { texto: 'La vida es como un viaje; cada experiencia es un aprendizaje.', autor: 'Anónimo' },
  { texto: 'El amor es la fuerza que todo lo conecta.', autor: 'Anónimo' },
  { texto: 'La esperanza es la que nos da alas.', autor: 'Anónimo' },
  { texto: 'La vida es como un libro; escribe tu propia historia.', autor: 'Anónimo' }
]

const handler = async (m, { conn }) => {
  const frase = FRASES[Math.floor(Math.random() * FRASES.length)]

  await conn.sendMessage(m.chat, {
    text: [
      `╔══〔 🌼 *THEELY-MD — FRASE* 〕══╗`,
      `║`,
      `║ 💬 *"${frase.texto}"*`,
      `║`,
      `║ ✍️ — ${frase.autor}`,
      `║`,
      `╚══════════════════════════════════╝`
    ].join('\n')
  }, { quoted: m })

  await m.react('✨')
}

handler.help    = ['frase']
handler.tags    = ['fun']
handler.command = ['frase', 'quote', 'motivacion']
handler.desc    = 'Frase motivacional o de anime aleatoria'
export default handler