const handler = async (m, { conn }) => {
  const factos = [
    'Los pulpos tienen 3 corazones y 9 cerebros.',
    'Las huellas dactilares de los koalas son casi idénticas a las humanas.',
    'Un día en Venus dura más que un año en Venus.',
    'Los elefantes son los únicos mamíferos que no pueden saltar.',
    'Las abejas pueden volar a 25 km/h.',
    'El corazón de una ballena azul pesa 600 kg.',
    'Los humanos comparten el 60% del ADN con las bananas.',
    'Un relámpago puede calentar el aire a 30,000°C.',
    'Los flamingos nacen grises y se vuelven rosados por su dieta.',
    'El ojo de un avestruz es más grande que su cerebro.',
    'La Vía Láctea tiene 100,000 millones de estrellas.',
    'El agua hirviendo se congela más rápido que el agua fría en el espacio.',
    'Los gatos pueden hacer 100 sonidos distintos, los perros solo 10.',
    'El árbol más viejo del mundo tiene 9,500 años.',
    'La risa es contagiosa como el bostezo.',
    'Un litro de agua pesa 1 kg, pero un litro de hielo pesa 0.92 kg.',
    'Los dedos de los pies nunca se rompen si no se usan zapatos.',
    'El polvo de tu casa es en parte piel muerta humana.',
    'Las jirafas tienen el mismo número de vértebras en el cuello que los humanos (7).',
    'El 90% de las células de tu cuerpo no son humanas, son bacterias.',
    'El cerebro humano genera más impulsos eléctricos en un día que todos los teléfonos del mundo juntos.',
    'Cuando mueres, tu cerebro sigue activo por unos minutos y puedes escuchar a los médicos declarar tu muerte.',
    'El amor libera las mismas sustancias químicas que la cocaína.',
    'Tu corazón late aproximadamente 100,000 veces al día, y nunca descansa.',
    'Los sueños son la forma en que tu cerebro procesa emociones y recuerdos mientras duermes.',
    'El dolor emocional activa las mismas áreas del cerebro que el dolor físico.',
    'La soledad tiene un impacto en la salud similar al de fumar 15 cigarrillos al día.',
    'Las personas que practican la gratitud son más felices y viven más tiempo.',
    'El 85% de las preocupaciones que tenemos nunca llegan a suceder.',
    'El miedo es una ilusión, pero el coraje es una decisión.',
    'El tiempo parece pasar más rápido a medida que envejecemos porque cada año es un porcentaje menor de nuestra vida.',
    'La felicidad no es algo que se encuentra, sino que se construye.',
    'El perdón no cambia el pasado, pero agranda el futuro.',
    'Las personas que más te critican son las que más necesitan tu amor.',
    'No hay mayor riqueza que la paz interior.',
    'La vida es 10% lo que te sucede y 90% cómo reaccionas.',
    'El propósito de la vida no es ser feliz, sino ser útil, honorable y compasivo.',
    'La gente olvidará lo que dijiste, pero nunca olvidarán cómo los hiciste sentir.',
    'El éxito no es la clave de la felicidad, la felicidad es la clave del éxito.',
    'La verdadera amistad no se mide por la cantidad de tiempo juntos, sino por la calidad.',
    'A veces la persona que más te ama es la que nunca te lo dice.',
    'El silencio a veces es la mejor respuesta.',
    'No todo lo que brilla es oro, pero todo lo que es oro brilla.',
    'El amor propio es el inicio de un romance duradero.',
    'La vida es una obra de teatro que no se ensaya.',
    'La mayor aventura es vivir la vida que sueñas.',
    'El mejor momento para plantar un árbol fue hace 20 años, el segundo mejor es ahora.',
    'No hay camino hacia la paz, la paz es el camino.',
    'La felicidad no es tener mucho, sino desear poco.',
    'El ego es el enemigo de la conexión humana.',
    'El verdadero lujo es tener tiempo para ti.',
    'La mente es como un jardín, si no la cultivas, crecen malas hierbas.',
    'El poder no está en la fuerza, sino en la capacidad de adaptarse.',
    'El amor es la fuerza más poderosa del universo.',
    'La vida es un 10% lo que te pasa y un 90% cómo lo interpretas.',
    'La paciencia es la compañera de la sabiduría.',
    'La humildad no es pensar menos de ti, sino pensar menos en ti.',
    'El enojo es un veneno que bebes esperando que el otro muera.',
    'La compasión es el puente que conecta los corazones.',
    'La bondad es la única inversión que nunca falla.',
    'La risa es la distancia más corta entre dos personas.',
    'El tiempo perdido nunca se recupera, pero se puede aprender.',
    'Cada día es una nueva oportunidad para empezar de nuevo.',
    'El pasado no define tu futuro, solo tu presente.',
    'La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento.',
    'La verdadera belleza está en el interior, pero el exterior es su reflejo.',
    'El conocimiento te hace fuerte, pero la sabiduría te hace libre.',
    'El amor no se encuentra, se construye con pequeñas acciones.',
    'Los momentos simples son los que más perduran en la memoria.',
    'La autenticidad es el mayor regalo que puedes dar al mundo.',
    'La confianza se gana con acciones, no con palabras.',
    'El fracaso es solo una parada en el camino al éxito.',
    'No hay mal que por bien no venga, si aprendes la lección.',
    'El corazón tiene razones que la razón no entiende.',
    'El alma no tiene edad, solo experiencia.',
    'La vida es como una cámara, enfoca lo bueno y revela los momentos.',
    'La felicidad es un viaje, no un destino.',
    'El amor es la única magia que realmente existe.',
    'La esperanza es el sueño del hombre despierto.',
    'La duda es el principio de la sabiduría.',
    'La perseverancia es la madre de los logros.',
    'El respeto se gana, no se exige.',
    'La sencillez es la máxima sofisticación.',
    'La vida es corta, pero el legado perdura.',
    'No hay mayor riqueza que una conciencia tranquila.',
    'El mejor regalo que puedes dar es tu atención.',
    'La libertad es la capacidad de elegir tu camino.',
    'El arte es la expresión del alma humana.',
    'La música es el lenguaje universal del alma.',
    'La poesía es la belleza hecha palabra.',
    'La naturaleza es el mejor sanador.',
    'El mar es el espejo del alma.',
    'El cielo nos recuerda que siempre hay algo más allá.',
    'Las estrellas son los sueños que iluminan la noche.',
    'El sol nos enseña que siempre hay un nuevo amanecer.',
    'La luna nos habla de ciclos y renovación.',
    'La tierra nos sostiene y nos pide cuidado.',
    'El fuego purifica y transforma.',
    'El agua fluye y nos enseña a adaptarnos.',
    'El viento nos lleva y nos recuerda que todo cambia.',
    'La vida es un constante fluir, como un río.',
    'Los árboles son los testigos silenciosos de la historia.',
    'Las montañas nos muestran la grandeza de la naturaleza.',
    'Los animales nos enseñan sobre lealtad y amor incondicional.',
    'Las flores nos hablan de belleza efímera.',
    'El amanecer nos da esperanza, el atardecer nos da paz.',
    'La noche nos invita a la introspección.',
    'El amor propio es el primer paso para amar a otros.',
    'La vulnerabilidad es la puerta a la conexión auténtica.',
    'El coraje no es la ausencia de miedo, sino la decisión de actuar a pesar de él.',
    'La gratitud transforma lo que tenemos en suficiente.',
    'La generosidad enriquece tanto al que da como al que recibe.',
    'La honestidad es la base de toda relación verdadera.',
    'La lealtad es un tesoro que no tiene precio.',
    'La compasión es la respuesta al sufrimiento del otro.',
    'La empatía nos permite sentir el corazón del otro.',
    'La solidaridad es la fuerza de la humanidad.',
    'La unidad es el camino hacia un mundo mejor.',
    'La paz empieza con una sonrisa.',
    'La alegría es un estado de ser, no de tener.',
    'La serenidad es la cima de la sabiduría.',
    'El equilibrio es la clave de la salud.',
    'La armonía es el canto de la vida.',
    'La verdad es la luz que disipa las tinieblas.',
    'La justicia es el pilar de la convivencia.',
    'La igualdad es el sueño de la humanidad.',
    'La diversidad es la riqueza del mundo.',
    'La belleza está en los ojos de quien mira con amor.',
    'La bondad es el idioma que los sordos pueden oír y los ciegos ver.',
    'El amor es la respuesta a todas las preguntas.',
    'La vida es un regalo, no un derecho.',
    'El tiempo es el bien más preciado, úsalo bien.',
    'La memoria es el diario del alma.',
    'Los sueños son el mapa hacia nuestro destino.',
    'Las metas son los faros que guían nuestra nave.',
    'El esfuerzo es el precio del éxito.',
    'La disciplina es el puente entre sueños y realidad.',
    'La pasión es el combustible de los grandes logros.',
    'La creatividad es la chispa de la innovación.',
    'La curiosidad es el motor del aprendizaje.',
    'La enseñanza es el arte de sembrar conocimiento.',
    'El aprendizaje nunca termina, la vida es una escuela.',
    'La sabiduría es la aplicación del conocimiento.',
    'La intuición es la voz del alma.',
    'La fe es la certeza de lo que no se ve.',
    'La esperanza es el aliento de la vida.',
    'El optimismo es el imán de la buena fortuna.',
    'La resiliencia es la capacidad de renacer.',
    'La fuerza no es física, es la del espíritu.',
    'La voluntad es la fuerza que mueve montañas.',
    'El carácter es lo que haces en la oscuridad.',
    'La reputación es lo que otros dicen, el carácter es lo que eres.',
    'La integridad es la coherencia entre lo que piensas, dices y haces.',
    'La honestidad intelectual es la base de la verdad.',
    'La humildad es la corona del sabio.',
    'La paciencia es la virtud de los fuertes.',
    'La tolerancia es el respeto por las diferencias.',
    'La empatía es el corazón de la compasión.',
    'La amabilidad es la cortesía del alma.',
    'La gentileza es la delicadeza de la fuerza.',
    'La cortesía es la flor de la educación.',
    'La urbanidad es el arte de vivir en sociedad.',
    'La civilidad es el pacto de la convivencia.',
    'La democracia es el gobierno del pueblo, para el pueblo.',
    'La libertad es el derecho a ser tú mismo.',
    'La justicia social es la equidad para todos.',
    'La igualdad de oportunidades es el sueño de la meritocracia.',
    'La diversidad cultural es la paleta del mundo.',
    'La interculturalidad es el diálogo de las culturas.',
    'La paz mundial empieza con la paz interior.',
    'La no violencia es la fuerza más poderosa.',
    'El diálogo es el puente de la entendimiento.',
    'La negociación es el arte del acuerdo.',
    'La conciliación es la síntesis de las diferencias.',
    'La armonía social es el balance de las partes.',
    'El bien común es el propósito de toda sociedad.',
    'La solidaridad internacional es la fraternidad de los pueblos.',
    'La ayuda humanitaria es la mano que alivia.',
    'La cooperación es el motor del progreso.',
    'La sostenibilidad es el respeto por el futuro.',
    'El cuidado del medio ambiente es la responsabilidad de todos.',
    'La ecología es la ciencia de la casa común.',
    'La biodiversidad es la red de la vida.',
    'La protección de la naturaleza es la defensa de la vida.',
    'El consumo responsable es la elección consciente.',
    'La reducción de residuos es el primer paso.',
    'El reciclaje es la transformación creativa.',
    'La reutilización es la práctica de la creatividad.',
    'La economía circular es el modelo del futuro.',
    'La energía renovable es la esperanza limpia.',
    'La eficiencia energética es la inteligencia aplicada.',
    'La movilidad sostenible es el camino verde.',
    'La alimentación saludable es la base de la vida.',
    'La hidratación es la fuente de la energía.',
    'El descanso es el reparador del cuerpo.',
    'La actividad física es el movimiento de la vida.',
    'La salud mental es el equilibrio emocional.',
    'La meditación es el silencio que sana.',
    'El yoga es la unión del cuerpo y el alma.',
    'La respiración consciente es la clave de la calma.',
    'La atención plena es el arte del presente.',
    'El mindfulness es la práctica de la conciencia.',
    'La neurociencia nos revela los misterios del cerebro.',
    'La psicología nos enseña la complejidad del ser.',
    'La sociología nos muestra la trama social.',
    'La antropología nos explora la diversidad humana.',
    'La filosofía nos invita a pensar.',
    'La ética es la brújula de la conducta.',
    'La moral es el código del bien y el mal.',
    'La espiritualidad es el anhelo de trascendencia.',
    'La religión es el camino hacia lo divino.',
    'El agnosticismo es la duda honesta.',
    'El ateísmo es la certeza de la razón.',
    'La ciencia es la luz del conocimiento.',
    'La tecnología es la herramienta del progreso.',
    'La innovación es la chispa del cambio.',
    'La educación es la base de la transformación.',
    'El arte es la expresión de la belleza interior.',
    'La literatura es el reflejo del alma humana.',
    'La poesía es la música de las palabras.',
    'La prosa es la narrativa de la vida.',
    'El cine es el espejo de la sociedad.',
    'La música es el lenguaje del sentimiento.',
    'La danza es la poesía del cuerpo.',
    'La pintura es la huella del color.',
    'La escultura es la forma del pensamiento.',
    'La arquitectura es el arte de los espacios.',
    'El diseño es la función de la belleza.',
    'La moda es la expresión de la identidad.',
    'La gastronomía es el arte del sabor.',
    'El vino es la poesía de la tierra.',
    'El café es el elixir del despertar.',
    'El té es la ceremonia de la calma.',
    'La cocoa es el regalo de los dioses.',
    'El amor es el mayor de los misterios.'
  ]

  const fact = factos[Math.floor(Math.random() * factos.length)]

  await m.react('🤯')
  await m.reply([
    `╔══〔 🌼 *THEELY-MD — FACTO* 〕══╗`,
    `║`,
    `║  🔍 *Dato curioso:*`,
    `║`,
    `║  📝 ${fact}`,
    `║`,
    `║  🤯 *¿Sabías esto?*`,
    `╚══════════════════════════════════╝`
  ].join('\n'))
}

handler.help = ['facto']
handler.tags = ['fun']
handler.command = ['facto', 'fact', 'dato']
handler.register = true
handler.desc = 'Dato curioso aleatorio'
export default handler